=== BartHelleman/Insurance/Insurerer/server/src/main/java/edu/avans/ivh5/server/resources/Clients.xsd
<?xml version="1.0" encoding="UTF-8"?>


<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="clients">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="client" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="BSN" type="xs:string"/>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="firstName" type="xs:string"/>
                            <xs:element name="city" type="xs:string"/>
                            <xs:element name="postcode" type="xs:string"/>
                            <xs:element name="address" type="xs:string"/>
                            <xs:element name="IBAN" type="xs:string"/>
                            <xs:element name="incasso" type="xs:boolean"/>
                            <xs:element name="email" type="xs:string"/>
                            <xs:element name="tel" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BartHelleman/Insurance/Insurerer/server/src/main/java/edu/avans/ivh5/server/resources/Clients.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<clients
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='Clients.xsd'>
    <client>
        <BSN>123456789</BSN>
        <name>Karatas</name>
        <firstName>Burak</firstName>
        <city>Utrecht</city>
        <postcode>1234AB</postcode>
        <address>Blabla</address>
        <IBAN>NL00XXXX0000009000</IBAN>
        <incasso>false</incasso>
        <email>b.karatas0@gmail.com</email>
        <tel>12346589</tel>
    </client>
	    
	<client>
        <BSN>485674958</BSN>
        <name>Bakels</name>
        <firstName>Rico</firstName>
        <city>Biervliet</city>
        <postcode>3143JB</postcode>
        <address>Ergens</address>
        <IBAN>NL30RABO0234009114</IBAN>
        <incasso>true</incasso>
        <email>RicoBakels@hotmail.com</email>
        <tel>0667594857</tel>
    </client>
</clients>
