=== BartHelleman/Insurance/Insurerer/server/src/main/java/edu/avans/ivh5/server/resources/InsuranceCompanies.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="companies">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="company" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="name"/>
              <xs:element type="xs:string" name="city"/>
              <xs:element type="xs:string" name="postcode"/>
              <xs:element type="xs:string" name="address"/>
              <xs:element type="xs:string" name="KVK"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== BartHelleman/Insurance/Insurerer/server/src/main/java/edu/avans/ivh5/server/resources/InsuranceCompanies.xml
<?xml version="1.0" encoding="UTF-8"?>
<companies
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='InsuranceCompanies.xsd'>
    <company>
        <name>ZLM</name>
        <city>Breda</city>
        <postcode>1345FJ</postcode>
        <address>ergensstraat</address>
        <KVK>02423</KVK>
    </company>  
      
    <company>
        <name>ZEKUR</name>
        <city>Tilburg</city>
        <postcode>9283DJ</postcode>
        <address>Daarzostraat</address>
        <KVK>2346</KVK>
    </company>  
    
    <company>
        <name>Avero</name>
        <city>IJzendijke</city>
        <postcode>1094WI</postcode>
        <address>Hierstraat</address>
        <KVK>3495</KVK>
    </company>  
        
</companies>
