=== BartHelleman/Insurance/Insurerer/server/src/main/java/edu/avans/ivh5/server/resources/InsuranceContracts.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="contracts">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="contract" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="BSN"/>
              <xs:element type="xs:string" name="clientName"/>
              <xs:element type="xs:decimal" name="ownRisk"/>
              <xs:element type="xs:integer" name="insuranceID"/>
              <xs:element type="xs:date" name="startDate"/>
              <xs:element type="xs:date" name="endDate"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== BartHelleman/Insurance/Insurerer/server/src/main/java/edu/avans/ivh5/server/resources/InsuranceContracts.xml
<?xml version="1.0" encoding="UTF-8"?>

<contracts
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='InsuranceContracts.xsd'>
    <contract>
        <clientName>Burak</clientName>
        <ownRisk>200</ownRisk>
        <insuranceID>001</insuranceID>
        <startDate>2015-10-10</startDate>
        <endDate>2016-12-10</endDate>
    </contract>    

    <contract>
        <clientName>Rico</clientName>
        <ownRisk>150</ownRisk>
        <insuranceID>002</insuranceID>
        <startDate>2015-09-15</startDate>
        <endDate>2016-11-18</endDate>
    </contract> 
    
    <contract>
        <clientName>Bart</clientName>
        <ownRisk>50</ownRisk>
        <insuranceID>003</insuranceID>
        <startDate>2015-08-05</startDate>
        <endDate>2016-12-28</endDate>
    </contract>           
</contracts>
