=== BartHelleman/Insurance/Insurerer/server/src/main/java/edu/avans/ivh5/server/resources/Invoices.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="invoices">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="invoice" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:integer" name="invoiceNumber"/>
                            <xs:element type="xs:date" name="date"/>
                            <xs:element type="xs:date" name="expirationDate"/>
                            <xs:element type="xs:decimal" name="VAT"/>
                            <xs:element type="xs:string" name="treatmentStatus"/>
                            <xs:element type="xs:string" name="BSN"/>
                            <xs:element type="xs:string" name="clientName"/>
                            <xs:element type="xs:string" name="clientAddress"/>
                            <xs:element type="xs:string" name="clientPostcodeCity"/>
                            <xs:element type="xs:string" name="companyName"/>
                            <xs:element type="xs:string" name="companyAddress"/>
                            <xs:element type="xs:string" name="companyPostcodeCity"/>
                            <xs:element type="xs:string" name="companyKVK"/>
                            <xs:element type="xs:string" name="amountSessions"/>
                            <xs:element type="xs:string" name="pricePerSession"/>
                            <xs:element type="xs:string" name="treatmentCode"/>
                            <xs:element type="xs:string" name="deductible"/>
                            <xs:element type="xs:string" name="amountToPay"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BartHelleman/Insurance/Insurerer/server/src/main/java/edu/avans/ivh5/server/resources/Invoices.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<invoices
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='Invoices.xsd'>
    <invoice>
        <invoiceNumber>100</invoiceNumber>
        <date>19-10-2015</date>
        <expirationDate>19-10-2016</expirationDate>
        <VAT>21</VAT>
    </invoice>
    
    <invoice>
        <invoiceNumber>200</invoiceNumber>
        <date>11-9-2015</date>
        <expirationDate>5-12-2016</expirationDate>
        <VAT>21</VAT>
    </invoice>
    
    <invoice>
        <invoiceNumber>300</invoiceNumber>
        <date>11-2-2015</date>
        <expirationDate>28-8-2016</expirationDate>
        <VAT>21</VAT>
    </invoice>

</invoices>
