=== BartHelleman/Insurance/Insurerer/server/src/main/java/edu/avans/ivh5/server/resources/TreatmentCodes.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="treatmentCodes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="treatmentCode" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="name"/>
              <xs:element type="xs:string" name="code"/>
              <xs:element type="xs:decimal" name="priceSession"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== BartHelleman/Insurance/Insurerer/server/src/main/java/edu/avans/ivh5/server/resources/TreatmentCodes.xml
<?xml version="1.0" encoding="UTF-8"?>
<treatmentCodes
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='TreatmentCodes.xsd'>
    <treatmentCode>
        <name>rugbehandeling</name>
        <code>001behandelcode001</code>
        <priceSession>15</priceSession>
    </treatmentCode>

    <treatmentCode>
        <name>nekbehandeling</name>
        <code>002behandelcode002</code>
        <priceSession>25</priceSession>
    </treatmentCode>
    
    <treatmentCode>
        <name>beenbehandeling</name>
        <code>003behandelcode003</code>
        <priceSession>10</priceSession>
    </treatmentCode>	    
    
</treatmentCodes>
